### ISSUE TITLE
Switch not working

### ISSUE THREAD

**Issue by snarlynarwhal** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#206] opened 2017-07-21 16:48 UTC
I copy and pasted code from the [switch](http://coreui.io/docs/new-components/switches) component documentation and modified it for React (changed 'class' to 'className' and added an 'onChange' handler) but it does not toggle when I click it (state and visuals remain the same).

**Comment by danielcoates** [comment] 2017-07-21 16:55
Can you post the code?

**Comment by snarlynarwhal** [comment] 2017-07-21 19:48
I am using React. Do I need any code to get it to toggle? My handler is just an empty function that logs 'click' atm. Should I post the entire component? Or just the render function?

**Comment by danielcoates** [comment] 2017-07-21 22:32
And that's where I'm out, I'm afraid I don't know the React version :(

**Comment by snarlynarwhal** [comment] 2017-07-24 15:14
Ah darn, well thanks for your willingness to help!

**Comment by milnomada** [comment] 2017-11-07 09:09
Hey @snarlynarwhal 

As you copied the code, it might still have checked attribute.

> I copy and pasted code from the switch component documentation and modified it for React

Remove the _checked_ attribute from the line:
`<input type="checkbox" className="switch-input" checked />`

It just works fine without it.

**Comment by xidedix** [comment] 2018-02-07 17:34
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2018-02-07 17:34 UTC
