### ISSUE TITLE
card collapse does not work on online demo form section 

### ISSUE THREAD

**Issue by khaninejad** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#306] opened 2017-12-04 12:21 UTC
http://coreui.io/demo/Static_Demo/components-forms.html
![works-notworks](https://user-images.githubusercontent.com/4404500/33552670-097a87cc-d90b-11e7-9f74-c1f94f1231d3.PNG)

**Comment by xidedix** [comment] 2017-12-22 12:34
Hi @khaninejad 
Thanks for letting us know! This will be fixed in the very next release.

**Comment by xidedix** [comment] 2018-02-07 17:00
fixed

**Comment by xidedix** [comment] 2018-02-07 17:00
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2018-02-07 17:00 UTC
