### ISSUE TITLE
Closing function of modal

### ISSUE THREAD

**Issue by masloord** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#283] opened 2017-10-11 09:02 UTC
unable to close the modal in typescript in angular 4 . Eg this.modal.hide()

**Comment by amayer5125** [comment] 2017-10-18 15:39
This should probably be an issue on [CoreUI-AngularJS](https://github.com/mrholek/CoreUI-AngularJS)

**Comment by scheinercc** [comment] 2017-10-19 06:32
It seems this page's live examples might got hit by this as well http://coreui.io/docs/components/modal/
Or is it something else? Tried it in Firefox Nightly, DevEdition and Chrome. Also the links within the Tooltips and popovers example don't work either.

**Comment by jmkni** [comment] 2017-10-19 08:30
+1

**Comment by mrholek** [comment] 2017-10-19 09:31
Hi in Angular 4 version we use this modal component: https://valor-software.com/ngx-bootstrap/#/modals

**Comment by scheinercc** [comment] 2017-10-19 11:24
That works fine for me in FF Nightly. As I said, not sure if the example from CoreUI.io is related or yet something else.

**Comment by xidedix** [comment] 2017-12-22 12:39
I'm closing this since the the issue is no longer active and it appear it was answered above. Please feel free to comment and reopen if the issue has not been resolved / the question has not been answered.

The CoreUI-Angular repository has been moved to the new location. 
[https://github.com/mrholek/CoreUI-Angular](https://github.com/mrholek/CoreUI-Angular)

**Closed by xidedix** 2017-12-22 12:39 UTC

**Comment by scheinercc** [comment] 2017-12-27 11:04
@xidedix - the modal issue in the documentation persist, but has likely nothing todo with the original request from @masloord. Where is the best place to file it? I couldn't find a repo for the documentation.
The page I refer to: http://coreui.io/docs/components/bootstrap-modal/ > "Live demo" > "Launch demo modal". It seems that there are several non-visible modals on top of the demo modal which makes all buttons unreachable. Tested with Firefox Nightly macOS and Safari
