### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by hickhub** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#298] opened 2017-11-10 13:37 UTC
Are the docs outdated?

At http://coreui.io/docs/getting-started/ajax-version/ it says install bower but on the missing files issue, you say you do not user bower.

**Comment by mrholek** [comment] 2017-11-10 13:38
We have to update it.

**Comment by hickhub** [comment] 2017-11-10 13:43
gulp serve on AJAX full project gives
module.js:544
    throw err;
    ^

Error: Cannot find module 'gulp-autoprefixer'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\playground\CoreUI\AJAX_Full_Project_GULP\gulpfile.js:6:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

**Comment by xidedix** [comment] 2017-11-10 15:40
please make sure that you have all dependencies installed
```bash
$ cd AJAX_Full_Project_GULP
$ npm i
```

**Comment by xidedix** [comment] 2017-12-22 12:22
I'm closing this since the the issue is no longer active and it appear it was answered above. Please feel free to  comment and reopen if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2017-12-22 12:22 UTC
