### ISSUE TITLE
Auto close menu in mobile view

### ISSUE THREAD

**Issue by moshefi** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#277] opened 2017-10-01 14:43 UTC
Currently, after navigating to a new route the menu is still open and must close manually

**Comment by xidedix** [comment] 2018-02-07 16:58
fixed in `1.0.8` and upward

**Comment by xidedix** [comment] 2018-02-07 17:02
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2018-02-07 17:02 UTC
