### ISSUE TITLE
Vue version, keep-alive does not work

### ISSUE THREAD

**Issue by tesla1060** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#269] opened 2017-09-20 13:49 UTC
Hi,
I did the following experiment,

I put `<keep-alive>` around 
`<router-view></router-view>`
both in `App.vue` and `Full.vue`

And put a `created` function
```
 created () {
    console.log('created called')
  }
```

 at the end of `Dashboard.vue`, as well a child component `Table.vue`.
> Start Up -> Dashboard.vue created() called

> Click Component.Table->Table.vue created() called
> Click Dashboard-> Nothing called
> Click Component.Table-> nothing called
> Click Component.Switch-> not created method
> Click Compoent.Table -> Table.vue created() called again. 

And if i keep on clicking between `Component.Switch` and `Component.Table`, the `created` method in `Table.vue` is always called.

May I know how to fix this to make `created` for `Table.vue` only be called for once?

**Comment by tesla1060** [comment] 2017-09-21 06:10
I think I have found a solution for this. 

replace 
`  render (c) { return c('router-view') }`
in the router definition,
with 
` render (c) { return c('keep-alive', [c('router-view')]) }`

**Comment by xidedix** [comment] 2017-12-22 12:27
I'm closing this since the the issue is no longer active and it appear it was answered above. Please feel free to comment and reopen if the issue has not been resolved / the question has not been answered.

The `CoreUI-Vue` repository has been moved to the new location. [https://github.com/mrholek/CoreUI-Vue](https://github.com/mrholek/CoreUI-Vue)

**Closed by xidedix** 2017-12-22 12:27 UTC
