### ISSUE TITLE
Dropdowns Groups not working

### ISSUE THREAD

**Issue by mcyhahaha** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#66] opened 2016-11-15 09:17 UTC
Dropdowns Groups not working in Angular2. No erros, no messages, no menu show.
and i check the demo http://coreui.io/demo/Angular2_Demo/#/dashboard 
![image](https://cloud.githubusercontent.com/assets/16377542/20299554/697830c2-ab56-11e6-8af0-a35fa94cf7e3.png) right setting button then no menu show too  

My brows is "chrown latest version" 

and I see the http://coreui.io/demo/Angular2_Demo/#/components/forms there is the basic use and I try to use the basic class is valide 

is there something error in dropdown menu class??

**Comment by wiflux** [comment] 2017-11-08 16:06
You can add below script for temporary fix.
```
$('body').on('click', '.dropdown-toggle', function(){
    if($(this).parent().hasClass('show')){
      $(this).next('.dropdown-menu').hide();
    }else{
      $(this).next('.dropdown-menu').show();
      $(this).blur(function(){ $(this).next('.dropdown-menu').hide(); });
    }
  });
```

**Comment by xidedix** [comment] 2018-02-07 16:52
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2018-02-07 16:52 UTC
