### ISSUE TITLE
Lack of demo

### ISSUE THREAD

**Issue by Qrzysio** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#234] opened 2017-08-14 15:08 UTC
> A fully functional demo is available at CoreUI

Well, I cannot find any demo on coreui.io.

**Comment by dushkostanoeski** [comment] 2017-08-14 15:16
Click on examples, and below you can choose one of the demos

**Comment by xidedix** [comment] 2018-02-07 17:05
[https://coreui.io/demos/](https://coreui.io/demos/)

**Comment by xidedix** [comment] 2018-02-07 17:05
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2018-02-07 17:05 UTC
