### ISSUE TITLE
Table classes seem broken in 1.0.4

### ISSUE THREAD

**Issue by ccoltman** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#288] opened 2017-10-24 23:44 UTC
- thead-default class doesn't style th elements

- table-responsive shrinks table data down to minimum, leaving huge whitespace to the right

**Comment by ccoltman** [comment] 2017-10-24 23:49
form-control-sm style missing

**Comment by ccoltman** [comment] 2017-10-25 01:56
OK I see now thead-default is now thead-light.  I see I can also assign breakpoints on table-responsive (i.e. table-responsive-sm), but I still think the table should be 100% width by using the default table-responsive

**Comment by Qrzysio** [comment] 2017-10-28 15:14
I also think `.table-responsive` should set the table full width. Bootstrap docs give us an option to use `.table-responsive` or `.table-responsive{sm,md,lg,xl}` (https://getbootstrap.com/docs/4.0/migration/#beta-2-changes). However if you try on pure Bootstrap 4.beta2 it's exactly the same. This should be mark as important change.

**Comment by xidedix** [comment] 2017-12-22 12:24
I'm closing this since the the issue is no longer active and it appear it was answered above. Please feel free to comment and reopen if the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2017-12-22 12:24 UTC
